### ISSUE TITLE
app.ts not recognized

### ISSUE THREAD

**Issue by EmmanuelMartinez** [tcampbPPU/ts-inertia-vue#2]
Hi, I changed the file extension 'app.js' to 'app.ts' and it doesn't load the localhost with vite,
I have already configured the entry in the vit.config.js file:

```
laravel({
      input: 'resources/js/app.ts',
      refresh: true,
    }),

```
but I have a message in the console: resources/js/app.js net::ERR_ABORTED 404 (Not Found)

could you help me solve it?

kind regards

**Comment by tcampbPPU** [comment]
Hi @EmmanuelMartinez I can try to assist but as a note this Repo (and blog) where created before the Laravel team introduce Typescript support for their Start Kit Laravel Breeze (which you can follow [here](https://laravel.com/docs/10.x/starter-kits#typescript))

If your `vite.config.js` looks a little like:
```
      laravel({
        input: 'resources/js/app.ts',
        refresh: true,
      }),
```
The next thing to check is making sure your `resources/views/app.blade.php` is using the proper script import:
```
        <!-- Scripts -->
        @routes
        @vite(['resources/js/app.ts', "resources/js/Pages/{$page['component']}.vue"])
        @inertiaHead
```

**Comment by EmmanuelMartinez** [comment]
@tcampbPPU  Thank you for the quick response.
Sorry for not mentioning it, the project is jetstream - inertia

I already made the change that you mention and I get the following error in screen:
```
Exception
Unable to locate file in Vite manifest: resources/js/app.ts.
```

**Comment by EmmanuelMartinez** [comment]
@tcampbPPU  
I found the error, I don't know why, but I made a document with the name 'app.ts ¡copy the content delete the previous one and it works. 😃

One more question in the app.ts, setup marks in error:
`The expected type comes from the "setup" property, which is declared here in the "CreateInertiaAppProps" type.`

the code:

` createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: name => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob<DefineComponent>('./Pages/**/*.vue')),
    setup({ el, App, props, plugin }) {
        return createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(ZiggyVue, Ziggy)
            .component('fa',FontAwesomeIcon)
            .mount(el);
    },
    progress: {
        color: '#4B5563',
    },
});`

any suggestions?
kind regards

**Comment by tcampbPPU** [comment]
Is this a Typescript or something like an ESlint error, I am not familiar with this issue, it also could depend on the contents of your `tsconfig.json` file

**Comment by EmmanuelMartinez** [comment]
@tcampbPPU  yes I think it is a mistake ESlint error.
I leave you some screenshots:
<img width="1270" alt="Captura de pantalla 2023-06-30 a la(s) 11 11 59" src="https://github.com/tcampbPPU/ts-inertia-vue/assets/23070204/99904970-8de5-4825-8267-b35c50ffbda1">
<img width="1001" alt="Captura de pantalla 2023-06-30 a la(s) 11 11 51" src="https://github.com/tcampbPPU/ts-inertia-vue/assets/23070204/9b1abb6f-7626-4da2-97c2-84dc2007908c">
<img width="1729" alt="Captura de pantalla 2023-06-30 a la(s) 11 11 43" src="https://github.com/tcampbPPU/ts-inertia-vue/assets/23070204/039e7ac9-2f92-4f25-aa23-31f652999429">

What do you recommend me?

**Comment by tcampbPPU** [comment]
ESlint errors depend on what your rules config is, getting warnings like that should not effect the build of the app
So you can just try removing ESlint are building/extending a config that better supports vue and typescript

**Comment by EmmanuelMartinez** [comment]
Thank you for your timely help, it was very useful.

Kind regards
